<?php

define('STATUS_USER_ACTIVE', 1);
define('STATUS_USER_PENDING', 4);

define('ROLE_USER_ADMIN', 1);
define('ROLE_USER_COURSE', 2);

define('STATUS_CLASS_ACTIVE', 1);
define('STATUS_CLASS_INACTIVE', 2);

define('STATUS_SUBJECT_ACTIVE', 1);
define('STATUS_SUBJECT_INACTIVE', 2);

define('SC_DATA_INVALID', 400);
define('SC_SERVER_ERROR', 500);
define('SC_SUCCESS', 200);
define('SC_QUERY_ERROR', 422);

define("MSG_DELETE_SUCCESS", "MSG_DELETE_SUCCESS")
?>
